repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/golangci/golangci-lint
    rev: v2.1.6
    hooks:
    -   id: golangci-lint
-   repo: local
    hooks:
    -   id: go-fmt
        name: go-fmt
        description: This hook runs go fmt.
        entry: go fmt ./...
        language: system
        types: [go]
    -   id: go-vet
        name: go-vet
        description: This hook runs go vet.
        entry: go vet ./...
        language: system
        types: [go]